version: '2'

services:

  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.15.10-alpine
    depends_on:
      - puddlejumper
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build/web:/srv/static:ro
    ports:
      - "80:80"

  puddlejumper:
    build:
      context: .
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "*"
      UPLOAD_LOCATION: file:///usr/src/app/data
      # UPLOAD_LOCATION: s3://dagrs-vrx/puddle
      # AWS_ACCESS_KEY_ID:
      # AWS_SECRET_ACCESS_KEY:
    volumes:
      - .:/usr/src/app/
      - ./data:/usr/src/app/data/
    ports:
      - "8000:8000"
