# Generated by Django 2.2 on 2019-04-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Code that vendors can use to upload files')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the file that was uploaded')),
                ('url', models.CharField(max_length=2083, verbose_name='URL to where the file is stored')),
                ('submitter', models.CharField(max_length=64, verbose_name='Name of the person/ thing that submitted the file')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField()),
                ('approved', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pj.Vendor')),
            ],
        ),
    ]
