# Generated by Django 2.2 on 2019-04-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(default=0, verbose_name='The size of the file in bytes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
    ]
