# Generated by Django 2.2 on 2019-04-08 18:11

from django.db import migrations, models
import server.pj.models


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0002_auto_20190405_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='code',
            field=models.CharField(default=server.pj.models.create_vendor_code, max_length=6, unique=True, verbose_name='Code that vendors can use to upload files'),
        ),
    ]
