# Generated by Django 2.2 on 2019-04-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0003_auto_20190408_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('Uploaded', 'UPLOADED'), ('Approved', 'APPROVED'), ('Processed', 'PROCESSED'), ('Transfered', 'TRANSFERED'), ('Failed', 'FAILED')], default='Uploaded', max_length=10),
        ),
    ]
