# Generated by Django 2.2 on 2019-04-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0004_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
