# Generated by Django 2.2 on 2019-04-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0006_auto_20190412_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='message',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Status details of file'),
        ),
    ]
