# Generated by Django 2.2 on 2019-04-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0007_file_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='message',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name="Additional notes about the file. This can include reasons it wasn't approved or why it failed processing"),
        ),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('Uploaded', 'UPLOADED'), ('Clean', 'CLEAN'), ('Approved', 'APPROVED'), ('Processed', 'PROCESSED'), ('Transferred', 'TRANSFERRED'), ('Failed', 'FAILED')], default='Uploaded', max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(max_length=2083, null=True, unique=True, verbose_name='URL to where the file is stored'),
        ),
    ]
