# Generated by Django 2.2 on 2019-04-17 18:46

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0008_auto_20190416_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='submitter',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(re.compile("^[A-Za-z1-9\\-\\s!_.*'()]*$"))], verbose_name='Name of the person/ thing that submitted the file'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(re.compile("^[A-Za-z1-9\\-\\s!_.*'()]*$"))]),
        ),
    ]
