# Generated by Django 2.2 on 2019-04-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0009_auto_20190417_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='key',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Path within the base location the file is stored'),
        ),
        migrations.AddField(
            model_name='file',
            name='location',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Base URL the file is stored at'),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('unscanned', 'unscanned'), ('clean', 'clean'), ('quarantined', 'quarantined'), ('approved', 'approved'), ('transferred', 'transferred'), ('failed', 'failed')], default='unscanned', max_length=11),
        ),
    ]
