# Generated by Django 2.2.1 on 2019-05-08 20:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0013_auto_20190507_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='submitter',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(re.compile("^[A-Za-z0-9\\-\\s!_.*'()]*$"))], verbose_name='Name of the person/thing that submitted the file'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='poc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pj.Stakeholder'),
        ),
    ]
