# Generated by Django 2.2.1 on 2019-05-22 17:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pj', '0014_auto_20190508_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Data source name')),
                ('data_origin', models.CharField(max_length=256, verbose_name='Source/origin of the data')),
                ('data_type', models.CharField(max_length=256, verbose_name='Type of the data')),
                ('date_information', models.DateField(verbose_name='Date of Information')),
                ('date_ingest', models.DateField(verbose_name='Date of Ingest')),
                ('entities', models.CharField(max_length=1028, verbose_name='Entities of the data source')),
                ('frequency', models.CharField(max_length=256, verbose_name='Frequency of data')),
                ('leads', models.CharField(max_length=256, verbose_name='Leads')),
                ('portfolio', models.CharField(max_length=1028, verbose_name='Portfolio for the data source')),
                ('priority', models.IntegerField(verbose_name='Priority of the data source')),
                ('request_method', models.CharField(max_length=256, verbose_name='Request method')),
                ('status', models.CharField(max_length=128, verbose_name='Status of the data source')),
                ('theme', models.CharField(max_length=128, verbose_name='Theme')),
                ('update_periodically', models.CharField(max_length=128, verbose_name='Update Periodically')),
            ],
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.CharField(blank=True, max_length=128, verbose_name='Title of todo')),
                ('text', models.TextField(verbose_name='Note Content')),
                ('status', models.CharField(max_length=128, verbose_name='Status of the todo')),
                ('created_at', models.DateTimeField(verbose_name='Date note created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Name of creater')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=256, verbose_name='Status')),
                ('note', models.TextField(verbose_name='Note Content')),
                ('created_at', models.DateTimeField(verbose_name='Date note created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Name of creater')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj.DataSource')),
            ],
        ),
    ]
