# Generated by Django 2.2.1 on 2019-05-22 17:38

from django.conf import settings
import django.core.validators
import re
from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Lower
import django.db.models.deletion
import server.pj.models

def lowercase_vendor_code(apps, schema_editor):
    Vendor = apps.get_model('pj', 'Vendor')
    Vendor.objects.update(code=Lower('code'))

def reverse_lowercase_vendor_code(apps, schema_editor):
    pass

def copy_vendor_name(apps, schema_editor):
    Vendor = apps.get_model('pj', 'Vendor')
    Vendor.objects.update(short_name=F('name'))

def reverse_copy_vendor_name(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pj', '0015_auto_20190522_1338'),
    ]

    operations = [
        migrations.RunPython(lowercase_vendor_code, reverse_lowercase_vendor_code),
        migrations.AddField(
            model_name='vendor',
            name='short_name',
            field=models.CharField(max_length=128, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile("^[A-Za-z0-9\\-\\s!_.*'()]*$"))]),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='code',
            field=models.CharField(default=server.pj.models.create_vendor_code, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-z0-9]+$'))], verbose_name='Code that vendors can use to upload files'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.RunPython(copy_vendor_name, reverse_copy_vendor_name),
        migrations.AlterField(
            model_name='vendor',
            name='short_name',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(re.compile("^[A-Za-z0-9\\-\\s!_.*'()]*$"))]),
        ),
    ]
