# Generated by Django 2.2.1 on 2019-05-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0016_auto_20190522_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.AddField(
            model_name='todo',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Status of the todo'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date note created'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date note created'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='lead',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Title of todo'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Note Content'),
        ),
    ]
