# Generated by Django 2.2.1 on 2019-06-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0017_auto_20190604_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='status',
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note Content'),
        ),
    ]
