# Generated by Django 2.2.1 on 2019-06-06 15:27

from django.db import migrations, models

def forward(apps, schema_editor):
    Vendor = apps.get_model("pj", "Vendor")
    for v in Vendor.objects.all():
        if v.poc:
            v.pocs.add(v.poc)
            v.poc = None
            v.save()

def backward(apps, schema_editor):
    Vendor = apps.get_model("pj", "Vendor")
    for v in Vendor.objects.all():
        if v.pocs.count() > 0:
            v.poc = v.pocs.first()
            v.pocs.set([])
            v.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0018_auto_20190605_1744'),
    ]

    operations = [
         migrations.AddField(
            model_name='vendor',
            name='pocs',
            field=models.ManyToManyField(blank=True, to='pj.Stakeholder'),
        ),
        migrations.RunPython(forward, backward),
        migrations.RemoveField(
            model_name='vendor',
            name='poc',
        )
    ]
