# Generated by Django 2.2.1 on 2019-06-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0019_auto_20190606_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='auto_approve',
            field=models.BooleanField(default=False, verbose_name='Approval of vendor files automatically or not'),
        ),
    ]
