# Generated by Django 2.2.1 on 2019-07-24 14:09

from django.db import migrations, models
import server.pj.models


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0021_vendor_approval_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='approval_regex',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[server.pj.models.validate_regex], verbose_name='Regex approval value'),
        ),
    ]
