# Generated by Django 2.2.1 on 2019-08-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0023_auto_20190729_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilenameCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Number of files with this name encountered')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='counter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pj.FilenameCounter'),
        ),
    ]
