# Generated by Django 2.2.1 on 2019-08-10 14:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0024_auto_20190806_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fragments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='Fragment identifier'), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='file',
            name='counter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pj.FilenameCounter'),
        ),
    ]
