# Generated by Django 2.2.1 on 2019-09-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0025_auto_20190810_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='date_information',
            field=models.DateField(null=True, verbose_name='Date of Information'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='date_ingest',
            field=models.DateField(null=True, verbose_name='Date of Ingest'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='entities',
            field=models.CharField(blank=True, default='', max_length=1028, verbose_name='Entities of the data source'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='frequency',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Frequency of data'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='leads',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Leads'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='portfolio',
            field=models.CharField(blank=True, default='', max_length=1028, verbose_name='Portfolio for the data source'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='priority',
            field=models.IntegerField(default=0, null=True, verbose_name='Priority of the data source'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='request_method',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Request method'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='update_periodically',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Update Periodically'),
        ),
    ]
