# Generated by Django 2.2.1 on 2019-09-05 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj', '0026_auto_20190904_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='priority',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, 'Priority cannot be below 1'), django.core.validators.MaxValueValidator(10, 'Priority cannot exceed 10')], verbose_name='Priority of file for processing order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='priority',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, 'Priority cannot be below 1'), django.core.validators.MaxValueValidator(10, 'Priority cannot exceed 10')], verbose_name='Default priority for files belonging to this vendor'),
        ),
    ]
